kind = "api"
previewPath = "/"
title = "Discotherm"
version = "1.0.0"
id = "3B4_FFSkEVBkAeYMFRJ2e"

[[services]]
localPort = 8080
name = "API Server"
paths = ["/"]

[services.development]
run = "sh -c 'cd ../../discoverability-check && exec python3 -m uvicorn main:app --host 0.0.0.0 --port 8080'"

[services.production]

[services.production.build]
args = ["sh", "-c", "pip install -r discoverability-check/requirements.txt"]

[services.production.run]
args = ["sh", "-c", "cd discoverability-check && exec python3 -m uvicorn main:app --host 0.0.0.0 --port 8080"]

[services.production.health.startup]
path = "/"
